version: '3'
services:
  banco:
    container_name: banco
    image: usuario/banco
    build: ./banco-docker
    ports:
      - "5433:5432"
  app-bandas:
    container_name: app-bandas
    image: usuario/app-bandas
    build: ./app-bandas
    ports:
      - "8080:8080"
    depends_on:
      - "banco"
    links:
      - "banco:host-banco"